
wut




Crawling website, starting at https://www.malwarebytes.com/sitemap.xml
link https://
            /pdf/datasheets/IncidentResponseSolutionBrief.pdf : HTTPSConnectionPool(host='%0a%20%20%20%20%20%20%20%20%20%20%20%20', port=443): Max retries exceeded with url: /pdf/datasheets/IncidentResponseSolutionBrief.pdf (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff05ba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
this url https://www.malwarebytes.com/casestudies/businessservices from https://www.malwarebytes.com/casestudies/business-services is broken with code 404
this url https://www.malwarebytes.com/casestudies/realestate from https://www.malwarebytes.com/casestudies/all-industries is broken with code 404
link https://boost : HTTPSConnectionPool(host='boost', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x111728ba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://jRegex : HTTPSConnectionPool(host='jregex', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11172ddd8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://Sparkle : HTTPSConnectionPool(host='sparkle', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11172d5f8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://Newtonsoft : HTTPSConnectionPool(host='newtonsoft', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x1117287f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://MSI2XML : HTTPSConnectionPool(host='msi2xml', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11172d5f8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://FindBugs : HTTPSConnectionPool(host='findbugs', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x111712f60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://Json-NET : HTTPSConnectionPool(host='json-net', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff1d518>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://sqllite : HTTPSConnectionPool(host='sqllite', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x111712c88>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://LinqToSqlExtensions : HTTPSConnectionPool(host='linqtosqlextensions', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11172ddd8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://apache-2 : HTTPSConnectionPool(host='apache-2', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff2d940>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
this url https://support.malwarebytes.com/docs/DOC-1962/support.malwarebytes.com from https://support.malwarebytes.com/docs/DOC-1962 is broken with code 404
Error in parsing url https://support.malwarebytes.com/servlet/JiveServlet/showImage/102-1871-6-7506/Home+Screen+001a.png, 'NoneType' object is not iterable
link https://libssh2 : HTTPSConnectionPool(host='libssh2', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fe7a978>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://SmartThreadPool : HTTPSConnectionPool(host='smartthreadpool', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fdd5828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://jzlib : HTTPSConnectionPool(host='jzlib', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff140b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://ImageComboBox : HTTPSConnectionPool(host='imagecombobox', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10feb9a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://Poco : HTTPSConnectionPool(host='poco', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fdd5828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://zlib : HTTPSConnectionPool(host='zlib', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff140b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://sph : HTTPSConnectionPool(host='sph', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff1dcf8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://CodeSnippet : HTTPSConnectionPool(host='codesnippet', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff1d048>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://7z : HTTPSConnectionPool(host='7z', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff1d668>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
this url http://www.aneyfamily.com/terryandann/post/2008/04/Batch-Updates-and-Deletes-with-LINQ-to-SQL.aspx from https://www.malwarebytes.com/support/thirdpartynotices is broken with code 404
link https://yaml-cpp : HTTPSConnectionPool(host='yaml-cpp', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff1d400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://DotObjects : HTTPSConnectionPool(host='dotobjects', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fde82e8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://Qt : HTTPSConnectionPool(host='qt', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10feb9a58>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://bcrypt-v1 : HTTPSConnectionPool(host='bcrypt-v1', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10feb9d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://SSKeyChain : HTTPSConnectionPool(host='sskeychain', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10feb9a58>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://SoapExtensionLib : HTTPSConnectionPool(host='soapextensionlib', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10feb9ac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link http://www.codekeep.net/snippets/04be377a-50fb-457a-8ac5-bace08f7cbd9.aspx : HTTPConnectionPool(host='www.codekeep.net', port=80): Max retries exceeded with url: /snippets/04be377a-50fb-457a-8ac5-bace08f7cbd9.aspx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x10ff1d128>, 'Connection to www.codekeep.net timed out. (connect timeout=3)'))
link https://OpenSSL : HTTPSConnectionPool(host='openssl', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fdd5160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://SerializableDictionary : HTTPSConnectionPool(host='serializabledictionary', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10feb97b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://bcrypt-v2 : HTTPSConnectionPool(host='bcrypt-v2', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff14358>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://InnoSetup : HTTPSConnectionPool(host='innosetup', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff14e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://DotNetZip : HTTPSConnectionPool(host='dotnetzip', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff143c8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://IPAddressControlLib : HTTPSConnectionPool(host='ipaddresscontrollib', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fe09e80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://AFNetworking : HTTPSConnectionPool(host='afnetworking', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fe090f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://sha256 : HTTPSConnectionPool(host='sha256', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10feb9ef0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://MS : HTTPSConnectionPool(host='ms', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff14cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://jquery : HTTPSConnectionPool(host='jquery', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fe090b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://vbAccelerator : HTTPSConnectionPool(host='vbaccelerator', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff14d68>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://Analytics-SDK-for-Android : HTTPSConnectionPool(host='analytics-sdk-for-android', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff14358>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://gmock-gtest : HTTPSConnectionPool(host='gmock-gtest', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff14d68>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://MixedCheckBoxesTreeView : HTTPSConnectionPool(host='mixedcheckboxestreeview', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff14cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://SqlHelper : HTTPSConnectionPool(host='sqlhelper', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff1d710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://ApplicationLoader : HTTPSConnectionPool(host='applicationloader', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff1dba8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://AFNetworkActivityLogger : HTTPSConnectionPool(host='afnetworkactivitylogger', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fe09828>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://HockeySDK : HTTPSConnectionPool(host='hockeysdk', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10fe090b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
this url https://www.malwarebytes.com/casestudies/miscellaneous from https://www.malwarebytes.com/casestudies/all-industries is broken with code 404
this url http://www.adr.org/arb_med%22%20%5Ct%20%22_blank from https://www.malwarebytes.com/eula is broken with code 404
link http://wikis.fenwick.com/sites/licensewiki/Shared%20Documents/AAA._commercial_demand%20.pdf%22%20%5Ct%20%22_blank : HTTPConnectionPool(host='wikis.fenwick.com', port=80): Max retries exceeded with url: /sites/licensewiki/Shared%20Documents/AAA._commercial_demand%20.pdf%22%20%5Ct%20%22_blank (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x10ff2dd30>, 'Connection to wikis.fenwick.com timed out. (connect timeout=3)'))
link http://wikis.fenwick.com/sites/licensewiki%22%20%5Ct%20%22_blank : HTTPConnectionPool(host='wikis.fenwick.com', port=80): Max retries exceeded with url: /sites/licensewiki%22%20%5Ct%20%22_blank (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x111712358>, 'Connection to wikis.fenwick.com timed out. (connect timeout=3)'))
link https://
            /pdf/datasheets/EndpointProtectionSolutionBrief.pdf : HTTPSConnectionPool(host='%0a%20%20%20%20%20%20%20%20%20%20%20%20', port=443): Max retries exceeded with url: /pdf/datasheets/EndpointProtectionSolutionBrief.pdf (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x11172d780>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://pdf/casestudies/CaseStudyColoradoSprings.pdf : HTTPSConnectionPool(host='pdf', port=443): Max retries exceeded with url: /casestudies/CaseStudyColoradoSprings.pdf (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff19048>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https:// /support/releasehistory/business : HTTPSConnectionPool(host='%20', port=443): Max retries exceeded with url: /support/releasehistory/business (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x111712470>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://trial : HTTPSConnectionPool(host='trial', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff2db00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
link https://download : HTTPSConnectionPool(host='download', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x10ff2db00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
this url https://support.malwarebytes.com/customer/portal/topics/802695-end-of-life-faq/articles?b_id=6441 from https://www.malwarebytes.com/securebackup is broken with code 404
link http://facebook.malwarebytes.com : HTTPConnectionPool(host='facebook.malwarebytes.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10fde85c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
this url https://www.malwarebytes.com/privacy/%20 from https://www.malwarebytes.com/pricing/inapp/pc is broken with code 404
link http://twitter.malwarebytes.com : HTTPConnectionPool(host='twitter.malwarebytes.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ff1d128>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
this url https://blog.malwarebytes.com/category from https://www.malwarebytes.com/thank_you is broken with code 404
this url https://staging-www.malwarebytes.com/casestudies/realestate from https://staging-www.malwarebytes.com/casestudies/all-industries is broken with code 404
this url https://staging-www.malwarebytes.com/casestudies/businessservices from https://staging-www.malwarebytes.com/casestudies/all-industries is broken with code 404
this url https://staging-www.malwarebytes.com/casestudies/miscellaneous from https://staging-www.malwarebytes.com/casestudies/all-industries is broken with code 404